name: NX_CI

on:
  push:
  pull_request:
  repository_dispatch:
    types: [run_build]

env:
  ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: true

jobs:
  build:
    runs-on: ubuntu-latest
    container: devkitpro/devkita64

    steps:
    - name: check out libnx
      uses: actions/checkout@v2
      with:
        repository: switchbrew/libnx
        ref: master

    - name: build libnx 
      run: |
        make -C nx -j2
        make install

    - uses: actions/checkout@v3

    - name: package
      run: ./build.sh

    - uses: actions/upload-artifact@v3
      with:
        path: dist/
