name: NX_CI

on:
  push:
  pull_request:
  repository_dispatch:
    types: [run_build]

env:
  ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: true

jobs:
  build:
    runs-on: ubuntu-latest
    container: devkitpro/devkita64

    steps:
    - uses: actions/checkout@v3

    - name: Install libnx
      run: |
        dkp-pacman -Syu --noconfirm
        dkp-pacman -S libnx --noconfirm
        apt-get install -y build-essential cmake git libarchive-dev libasound2-dev libavcodec-dev libavformat-dev libavutil-dev libbz2-dev libcurl4-openssl-dev libfreetype6-dev libjpeg-dev libmad0-dev libmp3lame-dev libogg-dev libpng-dev libpulse-dev libsdl2-dev libspeexdsp-dev libsqlite3-dev libtheora-dev libvorbis-dev libx264-dev libx265-dev libxvidcore-dev libi2c-dev i2c-tools 

    - name: package
      run: ./build.sh

    - uses: actions/upload-artifact@v3
      with:
        path: dist/