name: NX_CI

on:
  push:
  pull_request:
  repository_dispatch:
    types: [run_build]

env:
  ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: true

jobs:
  build:
    runs-on: ubuntu-latest
    container: devkitpro/devkita64

    steps:
    - uses: actions/checkout@v3

    - name: Install libnx
      run: |
        dkp-pacman -Syu --noconfirm
        dkp-pacman -S libnx --noconfirm
        dkp-pacman -Sy devkit-env devkitA64 libnx switch-tools switch-mesa switch-zlib switch-bzip2 switch-liblzma switch-freetype switch-libpng switch-libvpx switch-ffmpeg --noconfirm

    - name: package
      run: ./build.sh

    - uses: actions/upload-artifact@v3
      with:
        path: dist/