name: NX_CI

on:
  push:
  pull_request:
  repository_dispatch:
    types: [run_build]

env:
  ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: true

jobs:
  build:
    runs-on: ubuntu-latest
    container: 
      image: git.libretro.com:5050/libretro-infrastructure/libretro-build-libnx-devkitpro:latest

    steps:
    - uses: actions/checkout@v3

    - name: Mount sys-clk
      uses: actions/checkout@v3
      with:
        path: sys-clk

    - name: package
      working-directory: ./sys-clk
      run: ./build.sh

    - uses: actions/upload-artifact@v3
      with:
        path: dist/